### PR TITLE
add Git Credential Manager to features

### PR DESCRIPTION
**Pull request by hickford**
Describe Git Credential Manager in features list

Fixes https://github.com/git-for-windows/git/issues/4449

@ldennington @mjcheetham welcome to suggest a better description for this context.

### CODE REVIEW

**Comment by mjcheetham** [comment]
If you wanted an image to go along with the other features listed, here's one you can use. It's showing the basic username/password prompt for 'example.com'.
gcm-win-basic-sample

**Comment by dscho** [comment]
Good idea. @mjcheetham what about the wording, do you have any suggestions how to improve it?

**Comment by ldennington** [comment]
> Good idea. @mjcheetham what about the wording, do you have any suggestions how to improve it?

Perhaps we could re-use the description we have for the repo:

_Secure, cross-platform Git credential storage with authentication to GitHub, Azure Repos, and other popular Git hosting services._

Screenshot 2023-05-31 at 4 18 15 PM

**Comment by hickford** [comment]
Thanks! Updated text and added image.

**Pull request merged**
