### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by Raquib01**

### CODE REVIEW

**Comment by dscho** [comment]
Welcome to the Git for Windows project. Could you explain in a little bit of detail why this patch is needed?

**Comment by rimrul** [comment]
Conditional comments should(as the name implies) be comments. Removing the comment tags from them doesn't make sense.

**Comment by Raquib01** [comment]
bro please accept the pull request then you may undo things.
Actually we have to show our teachers at least two successful pull request.
please co-operate.

**Comment by rimrul** [comment]
Not gonna happen. Feel free to show this to your teacher as an example why this is a bad assignment that just leads to people like you submitting bullshit PRs that waste everyones time.

**Pull request closed without merging**
