### PR TITLE
Update screenshots

### PR DESCRIPTION
**Pull request by dscho**
Over in https://github.com/git-for-windows/git-for-windows.github.io/pull/28, @vtbassmatt [pointed out](https://github.com/git-for-windows/git-for-windows.github.io/pull/28#discussion_r752279516) that our screenshots do not have the same dimensions.

While looking into this, I realized that not only is that true, the screenshots are also of an ancient Git for Windows version, predating the v2.x era we're in since August 2015.

So let's update the screenshots. The diff is best viewed using the rich diff: 
image

While at it, automate generating the thumbnails.

### CODE REVIEW

**Comment by dscho** [comment]
One thing is a bit unclear to me: whether we want to have those super small thumbnails. I don't know that they make a lot of sense in this time and age of HiRes screens.

Thoughts?

**Comment by prertik** [comment]
Yeah, I also don't think we need to do those super small thumbnails.

**Comment by dscho** [comment]
> Yeah, I also don't think we need to do those super small thumbnails.

Do you know what the current story is on multiple resolutions, with regards to responsive design and mobile devices? I could imagine that we _should_ have thumbnails that are small enough that mobile phones do not have to deplete the battery just to scale down the screenshot. If that hunch is true, I wonder what the recommended size(s) is/are?

**Comment by vtbassmatt** [comment]
My go-to example for doing thumbnails and high-res stuff is Emojipedia. If you [pick an emoji](https://emojipedia.org/sparkles/) and then use web dev tools to "inspect" the PNG-based ones, you get something like:

```
<img src="https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/120/apple/285/sparkles_2728.png"
 srcset="https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/240/apple/285/sparkles_2728.png 2x" 
 alt="Sparkles on Apple iOS 14.6"
 width="120" height="120">
```

I believe this lets high-DPI clients pick a higher-res version while low-DPI clients save a little bandwidth.

**Comment by dscho** [comment]
> srcset

First time I came across that attribute. Here are the docs: https://html.com/attributes/img-srcset/

**Pull request merged**
