### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by Polostor**
Added Licenses subsection in Tools & Features section.
This should clarify under what license the products are and as well inform with more information (via FAQ#licenses link).

### CODE REVIEW

**Comment by dscho** [comment]
How about linking to https://github.com/git-for-windows/build-extra/blob/master/ReleaseNotes.md#licenses instead?

**Comment by dscho** [comment]
ping?

**Comment by Polostor** [comment]
Cheers, sorry was on vacation. 
I edited the index as you projected. Just moved the text to be the link :+1:

**Comment by dscho** [comment]
I like the idea of adding this link. I would like to see it done in a way that leaves text untangled, though:

footer-g4w-pr-14

**Comment by Polostor** [comment]
**Answer for the linked image**
I have tested whole thing under FF 53.0.2 and it does depend on size of window. Whereas this issue happens the same for other links when window is made smaller. 
Therefore my advice would be to play a bit more with cascade styles (in pack.css) for other sizes. I won't create another merge request for it as it is closely linked with this one. 

**Idea for the cascades issue in pack.css** 

- The file is not properly formatted (not a big one) 
- `@media screen and (max-width:700px)` is being set twice **!!!**

For this change the best scenario (from my point of view) is to adjust the size of `.content` according to page size eg:

```
... initial width settings of .content ...
.content {width: 65%;}

@media screen and (max-width: 1050px) {
.content {width: 80%;}
}

@media screen and (max-width: 880px) {
.content {width: 90%;}
}

@media screen and (max-width: 750px) {
.content {width: 100%; min-width: 690px;}
...fixed from (max-width: 700px)...
}
```

**Comment by dscho** [comment]
> Idea for the cascades issue in pack.css
> 
>     The file is not properly formatted (not a big one)

The file is actually generated from the other files in `css/` by cssmin.

**Comment by Polostor** [comment]
Hello, there is still one problem. Links in footer are still overlapping (with the Licenses link) because of - 
`@media screen and (max-width: 700px) {`
instead of correct one which should be 
`@media screen and (max-width: 750px) {`
@dscho I wrote it to [Merge branch 'style-fixes'](https://github.com/git-for-windows/git-for-windows.github.io/commit/6dff8ae8b457d5d5a639afd7dc41642c63184bdf) as comment

**Pull request merged**
