### PR TITLE
ReadMe: Encouraging instructions

### PR DESCRIPTION
**Pull request by PhilipOakley**
This contributor needed a little encouragement to believe that
supporting the development was that/this easy.

Add a few statements of encouragement to dispel user fears, such as
where 'npn' will come from.

This user tested on a Win XP Sp3 Netbook, so is much encouraged.

Signed-off-by: Philip Oakley <philipoakley@iee.org>

### CODE REVIEW

**Comment by dscho** [comment]
Excellent, thanks!

**Comment by PhilipOakley** [comment]
@dscho Thanks for including this. 

Silly question: What software do you you for preparing the front web page? I was thinking of adding a button/link to a section on 'Compatibilities 1.01' to cover all those 'obvious' (in)compatibilities that have to be answered (I know they are in the release notes / wiki / FAQs, but user education is never DRY ;-)

**Comment by dscho** [comment]
> What software do you you for preparing the front web page?

I [use](https://github.com/git-for-windows/build-extra/blob/ae3bd8053a63892d2460434c24c08983d5fc160b/please.sh#L691) the node.js provided by MSys2...

**Comment by PhilipOakley** [comment]
> > What software do you you for preparing the front web page?
> I use the node.js provided by MSys2...
Ah. maybe a misunderstanding. I thought (after a quick loook) that node is for the JS elements within the page, rather than the overall page design/layout.

I was more wondering about the page design / layout aspects; which is something I've not done much of (just occasional low level hacking of old style HTML), hence I was wondering what tool you use for that (e.g. adding another blue button..).  /-

Sorry for being so dumb on the moderm web front end stuff.....
--
Philip

**Comment by dscho** [comment]
> I was more wondering about the page design / layout aspects;

Well, I was lucky enough that two contributors worked on that. I am not so firm on web technology myself, these days :smile:

**Pull request merged**
