### PR TITLE
Update and rename jquery-1.10.2.min.js to jquery-1.11.3.min.js

### PR DESCRIPTION
**Pull request by paladox**
Upgrades to jquery-1.11.3

Please see release notes at http://blog.jquery.com/2014/01/24/jquery-1-11-and-2-1-released/

### CODE REVIEW

**Comment by dscho** [comment]
Thank you for your contribution.

I need to ask for a couple of improvements, though:

- Relative to the [official](https://jquery.com) jquery-1.11.3.min.js, the version added here has this extra line: `//# sourceMappingURL=jquery.min.map` (maybe there is a good reason to add that line?)
- Without appropriate changes in the `Gruntfile`, the upgrade will not work correctly
- The commit message is pretty empty. Instead, I would like to read a concise argument why the upgrade is needed (after chasing down a couple of links, I know it now, but readers of the commit should not need to do the same), and a paragraph with the analysis reassuring the reader that the new version will work with our [other](https://github.com/git-for-windows/git-for-windows.github.io/tree/master/js) two jquery files without problems.

**Comment by YueLinHo** [comment]
Is it better to split the commit into two commits?
One is for rename only, the other one is for modification.

**Comment by dscho** [comment]
@YueLinHo actually, the modification is *missing* from the commit: without modifying the Gruntfile, the commit is incomplete because it *breaks* the build.

**Comment by YueLinHo** [comment]
@dscho Thanks for telling me that.  :smile: 
The "modification" I say means the modification of **.min.js* itself.
I just think that it would be easily reviewed and traced.

**Comment by paladox** [comment]
Ok I have done it here https://github.com/git-for-windows/git-for-windows.github.io/pull/4

**Comment by paladox** [comment]
I do not think this will break it. but I am not sure. jquery 1.9 would break whereas 1.11.3 is an update that dosent break as much.

**Comment by paladox** [comment]
I copyed the jquery.js file for 1.11.3 so not sure. But should be kept just in case it breaks anything if removed.

**Comment by dscho** [comment]
> I copyed the jquery.js file for 1.11.3 so not sure. But should be kept just in case it breaks anything if removed.

Hmm. That does not give me the assurance I need to merge this. I need definitive, well-researched answers. I need a clear clarification why the line is there when it is not in the copy *I* downloaded. I need to see that my concerns regarding a breaking change are addressed (breaking something in one commit only to fix it in the next commit is not what I asked for, I asked to rewrite the first commit that was faulty). And lastly, I cannot merge this Pull Request if there has been no analysis whatsoever (or at least no public record of such an analysis) how our existing JQuery components fare with the upgrade. And please inspect the APIs used, do not just look over the result after running `grunt` and report that nothing obvious sticks out. That would not be good enough.

**Comment by paladox** [comment]
Hi could you set up a test folder and copy the whole content of the website and put it into that folder and then use this patch to see if it breaks anything. since I would not know. and well this upgrade is not as majour as 1.9.

**Comment by dscho** [comment]
@paladox Sorry, this is exactly the opposite of what I asked for. I need to be certain that you have looked at the code that is affected by the upgrade. That has obviously not been the case, so we just don't know if it breaks anything or not. I am not willing to accept such a change because I would be the one who would have to clean up the mess afterwards.

> I do not think this will break it. but I am not sure. jquery 1.9 would break whereas 1.11.3 is an update that dosent break as much.

This is exactly what I feared. It is unfortunately unacceptable to propose a change without knowing what it will break.

**Comment by paladox** [comment]
I mean test it without touching production. Like in a test folder. So that it doesent affect anyone and we could test since I would not be able to 100% tell you that anything breaks without testing it.

**Comment by dscho** [comment]
@paladox just testing it will fail to provide the analysis I asked for. You see, whatever you test, you probably forget to test that one thing that breaks in the end.

No, in order to fix this Pull Request, a diligent analysis has to be performed of the APIs used by our code, and whether they changed in JQuery 0.10.x -> 0.11.x.

**Comment by paladox** [comment]
Hi what code are looking to find out if it breaks if we upgrade jquery do you have links to the files you would like me to check.

**Comment by dscho** [comment]
Same link as I posted [originally](https://github.com/git-for-windows/git-for-windows.github.io/pull/3#issuecomment-113129911): https://github.com/git-for-windows/git-for-windows.github.io/tree/master/js

If in doubt, use `git grep`.

**Comment by paladox** [comment]
Ok thaks I looked at the files I doint think they would break it. But you should test because I carnt be 100% sure.

**Comment by dscho** [comment]
Frankly, I have no idea what to do with this Pull Request. The first commit still breaks the build, fixed by the second commit, and instead of having a reassuring analysis of our code and the required JQuery version, now a third commit changes yet another dependency, also without analysis. So instead getting more of what I asked for, I get more of the opposite :disappointed:

**Comment by dscho** [comment]
> The first commit still breaks the build, fixed by the second commit

To clarify, I already asked in the first comment to rewrite (amend) the first commit, and that has not happened.

**Comment by paladox** [comment]
Ok I have I added a bit more detail. and what would you like to know in the comment. The main changes.

**Comment by dscho** [comment]
The first commit still breaks the build.

**Comment by dscho** [comment]
Additionally, none of the commits have a sign off.

And none of the commit messages even so much as try to convince the reader that the introduced change is a good one. Just have a look at [this commit](https://github.com/git-for-windows/git-for-windows.github.io/commit/2ecd4089955a037c3ef901df916d82f54b089860) for example. It explains very well *why* the change was made and what the change is expected to fix. There is none of this in any of the three commits in this Pull Request.

In contrast, the answers my questions elicited make pretty clear that there is a very, very good chance that merging this Pull Request would completely break the functionality of this web site. I asked several times to please analyze this, and given that there has been no analysis in the first place, by now my trust has to be reinstated by a really thorough job (i.e. "I looked at it and it seems fine" does not do anything to reverse my impression, while I could be convinced by a list of JQuery functions used in our Javascript code along with a list of relevant changes in the JQuery API, accompanied by a link to the source of the information, all in a properly formatted and understandable commit message). There was not even anything in the way of "We need this change because JQuery 0.11.x fixes the critical bug XYZ, which affects us". This is disappointing.

By now, my impression is firmly that I already spent more time and diligence reviewing this Pull Request and #4 and asking questions and suggesting improvements than was spent on submitting the Pull Requests and addressing my concerns. I am sure you can do better than this, and it will be necessary to do better than this in order to get a future revision of this Pull Request merged.

**Pull request closed without merging**
