### PR TITLE
Update and rename jquery-1.10.2.min.js to jquery-1.11.3.min.js

### PR DESCRIPTION
**Pull request by paladox**
Ive updated jquery to 1.11.3. The update should not be as big as upgrading from 1.8 to 1.9. 1.10 to 1.11 I think is a minor update.

Also update grunt to 0.4.5.

Also add the jquery script to the top of index.html so when a jquery file is loaded this script will run.

### CODE REVIEW

**Comment by dscho** [comment]
Hi @paladox!

Thank you for your contribution.

A request, though: all of the commit messages are one liners that say *what* was done. But not why... So far, I do not know why anything should be updated for that reason. Could you fix that?

**Comment by paladox** [comment]
Ok done. Updated description.

**Comment by dscho** [comment]
Thanks. I still do not know *why* it is desirable to upgrade JQuery, though. Is it faster? Was a bug fixed?

**Comment by paladox** [comment]
I would think bugs are fixed and I would think they improved the performance but they added support for iOS 8. Not sure if iOS 9 is supported.

**Comment by dscho** [comment]
@paladox hrm. That does not fill me with confidence... I have had too many issues in my life due to blindly upgraded dependencies, even in Git for Windows. I'd rather only upgrade when it actually fixes a known bug. And when I can really verify easily that the files have not been tampered with (the diff is way too unwieldy to review).

**Pull request closed without merging**
